### ISSUE TITLE
Java Exception error

### ISSUE THREAD

**Issue by jlnhlfan** [toruzz/TileMolester#23]
![Screenshot_July_10_2024_11_58_29_AM](https://github.com/toruzz/TileMolester/assets/31529087/55d2a8e2-229a-4b1b-9ec4-84e5cc4020ee)

When using Java 8 411 to run version 0.21 of the porgram, I got this error message. I'm using WIndows 10.

Java 8 411 is the most recent version of Java that doesn't come exclusively in an SDK, by the way. So either I install a JDK and not use this program, or I use an older version instead, which would mean I won't have these:

New themes. Old custom system removed
Fractional scale support
New application icon
UX improvements
Dark mode toggle added
Edit color implemented
Tons of fixes and changes
Used Maven for building (PR by devnewton)

What do you recommend I should do?

**Comment by hupfdule** [comment]
The code is compiled for Java 17. So you need a Java version >= 17.

**Comment by jlnhlfan** [comment]
I tried that, but I couldn’t find an executable that would allow me to run .jar files in any version beyond Java 8.

**Comment by hupfdule** [comment]
I am not sure what you are missing. 

Each JDK should have a `java.exe` (under Windows) that is used to run the jar. Could be used from the commandline like that: `c:\Program Files\jdk17\java.exe c:\Program Files\TileMolester\tilemolester.jar`.

Maybe you want to double click on the jar to start it with java and the jar filetype is still associated with java 8? Then you have to reassociate it to the Java 17 (or whatever version of Java you are using) executable.

**Comment by wangsitan** [comment]
Oracle doesn't supply standalone JRE after java 8 (I'm not sure).

I met the same problem, and I found this:
https://stackoverflow.com/questions/55868821/when-jre-was-completely-discontinued-as-a-separate-offering

Then I downloaded JRE 23 from Azul Zulu:
https://www.azul.com/downloads/zulu-community/?&architecture=x86-64-bit&package=jre

Extract it, there are java and javaw under `bin` directory.

You can run jar program from cmdline:
```sh
PATH_OF_JRE/bin/java -jar tilemolester.jar
```

**Comment by jlnhlfan** [comment]
Thank you, Wang.
