### ISSUE TITLE
Please help 

### ISSUE THREAD

**Issue by sandmaansam** [toruzz/TileMolester#3]
<img width="550" alt="Error 2" src="https://user-images.githubusercontent.com/106861836/171989360-c59c9c4a-25d8-4dff-8483-4f968eb42971.png">
<img width="325" alt="Error 1" src="https://user-images.githubusercontent.com/106861836/171989361-595663f0-e5bb-4d18-aa46-6a5a28e718f7.png">

I'm have a problem launching the program I keep getting these 2 error messages when opening the program could you please help
[tile_molester_020 (1).zip](https://github.com/toruzz/TileMolester/files/8837244/tile_molester_020.1.zip)

**Comment by That-Human-Being** [comment]
This error is also happening for me (v16 & v20), I tried a few things such as:
- Reinstalling `openjdk`
- Running it in the terminal (openjdk shell)

No clue what's wrong...

**Comment by h57758** [comment]
I got it to work! Before i was using the JavaLauncher which went to a Java SE but now i tried with my Temuri n JDK 17 and it worked!

**Comment by jiaminglimjm** [comment]
Same, then I tried running the .jar file from the command line and it worked! `java -jar TileMolester.jar`

**Comment by h57758** [comment]
> Same, then I tried running the .jar file from the command line and it worked! `java -jar TileMolester.jar`

That’s actually the exact thing that I did to get it to work

**Comment by Ckosmick** [comment]
Yes when in doubt run `java -jar TileMolester.jar`. This ticket is good to close now.
