### ISSUE TITLE
How do i compile

### ISSUE THREAD

**Issue by ghost** [toruzz/TileMolester#4]
I'm wondering how to compile it.

I'm on an M1 Mac Mini running MacOS 12

And yes i tried `./compile.sh`.

I'm trying to change the theme from the MacOS System theme to Nimbus

**Comment by Ckosmick** [comment]
Looks like you figured this out already? #5

**Comment by DoctorMikeReddy** [comment]
They may have, but I haven't. Can you advise?

**Comment by DoctorMikeReddy** [comment]
I have manually copied the resources icons, etc, to the right folder heirarchy, but TMUI.java uses com.oracle.tools.packager.Log and I can only run OpenJDK, which obviously does not have Oracle libraries
